import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { chmod, lstat, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { initializeWindowsVmRoot } from "../scripts/windows-vm.mjs";
import { generateWindowsUnattend } from "../scripts/windows-unattend.mjs";
import { createWindowsAnswerMedia } from "../scripts/windows-installer-media.mjs";
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."), templates=path.join(repo,"templates","windows");
const input={account:"opemostest",password:"local-onetime-A9!",sshPublicKey:`ssh-ed25519 ${Buffer.alloc(32,8).toString("base64")} test`};
async function fixture(){const parent=await mkdtemp(path.join(os.tmpdir(),"opemos-answer-media-")),root=path.join(parent,"windows-vm");await initializeWindowsVmRoot(root);const file=path.join(root,"runtime","provision-input.json");await writeFile(file,JSON.stringify(input),{mode:0o600});await generateWindowsUnattend(root,file,templates);return{parent,root};}
function runner({code=0,bytes=Buffer.from("fake answer ISO"),mode=0o600,onSpawn=()=>{} }={}){return(command,args,options)=>{onSpawn(command,args,options);const child=new EventEmitter();child.stderr=new EventEmitter();queueMicrotask(async()=>{if(bytes)await writeFile(args[args.indexOf("-o")+1],bytes,{mode});if(code)child.stderr.emit("data",Buffer.from("bounded failure"));child.emit("close",code)});return child}}
test("answer media builder uses the exact reviewed genisoimage invocation",async()=>{const f=await fixture();try{const generated=path.join(f.root,"generated"),output=path.join(generated,"opemos-windows-answer.iso");let spawn;const out=await createWindowsAnswerMedia(f.root,runner({onSpawn:(command,args,options)=>{spawn={command,args,options}}}));assert.deepEqual(spawn,{command:"genisoimage",args:["-quiet","-J","-R","-V","OPEMOS_ANSWER","-o",output,"-graft-points",`autounattend.xml=${path.join(generated,"autounattend.xml")}`,`opemos-provision.ps1=${path.join(generated,"provision.ps1")}`],options:{stdio:["ignore","ignore","pipe"]}});assert.equal(out.status,"created");assert.equal(out.filename,"opemos-windows-answer.iso");assert.equal(out.size,15);assert.match(out.sha256,/^[0-9a-f]{64}$/);await assert.rejects(createWindowsAnswerMedia(f.root,runner()),/EEXIST/)}finally{await rm(f.parent,{recursive:true,force:true})}});
test("answer media builder rejects changed or permissive inputs before launch",async()=>{for(const change of ["mode","shape","binding-shape","script-mismatch"]){const f=await fixture();try{const answer=path.join(f.root,"generated","autounattend.xml");if(change==="mode")await chmod(answer,0o644);else if(change==="shape")await writeFile(answer,"<unattend/>",{mode:0o600});else if(change==="binding-shape")await writeFile(answer,(await readFile(answer,"utf8")).replace("$v.Count -ne 1","$v.Count -lt 1"),{mode:0o600});else await writeFile(path.join(f.root,"generated","provision.ps1"),"changed",{mode:0o600});let called=false;await assert.rejects(createWindowsAnswerMedia(f.root,()=>{called=true}),/mode-0600|not bound|reviewed generated shape/);assert.equal(called,false)}finally{await rm(f.parent,{recursive:true,force:true})}}});
test("answer media builder removes only failed output",async()=>{const f=await fixture();try{await assert.rejects(createWindowsAnswerMedia(f.root,runner({code:9})),/bounded failure/);await assert.rejects(readFile(path.join(f.root,"generated","opemos-windows-answer.iso")));assert.match(await readFile(path.join(f.root,"generated","provision.ps1"),"utf8"),/OpenSSH/)}finally{await rm(f.parent,{recursive:true,force:true})}});
test("answer media builder makes tool-created output private independent of umask",async()=>{const f=await fixture();try{await createWindowsAnswerMedia(f.root,runner({mode:0o644}));const info=await lstat(path.join(f.root,"generated","opemos-windows-answer.iso"));assert.equal(info.mode&0o777,0o600)}finally{await rm(f.parent,{recursive:true,force:true})}});
test("answer media builder removes output when permission hardening fails",async()=>{const f=await fixture();try{await assert.rejects(createWindowsAnswerMedia(f.root,runner(),async()=>{throw new Error("chmod denied")}),/chmod denied/);await assert.rejects(readFile(path.join(f.root,"generated","opemos-windows-answer.iso")))}finally{await rm(f.parent,{recursive:true,force:true})}});
test("answer file binds one OPEMOS_ANSWER volume to the generated script digest",async()=>{const template=await readFile(path.join(templates,"autounattend.xml.template"),"utf8");for(const expected of [/Get-Volume/,/FileSystemLabel -ceq &apos;OPEMOS_ANSWER&apos;/,/\$v\.Count -ne 1/,/DriveLetter/,/opemos-provision\.ps1/,/Get-FileHash -LiteralPath \$p -Algorithm SHA256/,/__PROVISION_SHA256__/,/exit 31/,/exit 32/,/exit 33/,/exit 34/,/&amp; \$p/])assert.match(template,expected);assert.doesNotMatch(template,/Select-Object -First|Get-PSDrive|C:\\OPEMOS\\provision/)});
