export const SUPPORTED_LOCALES = Object.freeze(["en-US", "de-DE", "ja-JP", "ar"]);
const STORAGE_KEY = "opemos.locale";
const en = {
  language:"Language",systemDefault:"System default",languageHelp:"Choose an interface language or follow the system locale.",dialogTitle:"Core compatibility inspector",close:"Close",notice:"Read-only preview. Document structure is checked, but authenticity is not. A compatible result here does not authorize a build, download, or activation.",fileOpen:"Open a local resolver JSON file (up to 1 MiB)",documentLabel:"Core resolver JSON (up to 1 MiB)",placeholder:"Paste a Core resolver result",inspect:"Inspect pasted result",clear:"Clear",fixtureHelp:"Development fixtures are non-production and available only in debug builds.",compatibleFixture:"Compatible fixture",noArtifactFixture:"No-artifact fixture",privacy:"Selected file and pasted content are processed locally and cleared when this inspector closes. No credentials, downloads, cache changes, or guest operations are needed.",noResult:"No result loaded.",checking:"Checking document structure…",unverified:"Unverified document",development:"Development fixture — non-production",notProvided:"Not provided",none:"None",truncated:"truncated for display",coreStatus:"Core status",steamosTarget:"SteamOS target",kernelTarget:"Kernel target",architecture:"Architecture",exactSupport:"Exact-target support reported by Core",reason:"Reason",message:"Message",publicationTag:"Publication tag",publishedSteamOS:"Published SteamOS",publishedKernel:"Published kernel",publishedNvidia:"Published NVIDIA",artifactName:"Artifact name",artifactTrust:"Artifact trust reported by Core",requiredVerification:"Required verification",nextAction:"Next action reported by Core",actionArchitecture:"Action architecture",kernelPolicy:"Kernel policy",availableGenerations:"Available generations — development fixture",selectedGeneration:"Selected generation — development fixture",activeGeneration:"Active generation — development fixture",lastKnownGood:"Last-known-good generation — development fixture"
};
const catalogs = {
  "en-US": en,
  "de-DE": {...en,language:"Sprache",systemDefault:"Systemstandard",languageHelp:"Oberflächensprache wählen oder der Systemsprache folgen.",dialogTitle:"Core-Kompatibilität prüfen",close:"Schließen",notice:"Schreibgeschützte Vorschau. Die Dokumentstruktur wird geprüft, die Echtheit jedoch nicht. Ein kompatibles Ergebnis erlaubt weder Build noch Download oder Aktivierung.",fileOpen:"Lokale Core-Resolver-JSON-Datei öffnen (bis 1 MiB)",documentLabel:"Core-Resolver-JSON (bis 1 MiB)",placeholder:"Core-Resolver-Ergebnis einfügen",inspect:"Eingefügtes Ergebnis prüfen",clear:"Leeren",fixtureHelp:"Entwicklungsbeispiele sind nicht für die Produktion bestimmt und nur in Debug-Builds verfügbar.",compatibleFixture:"Kompatibles Beispiel",noArtifactFixture:"Beispiel ohne Artefakt",privacy:"Ausgewählte Dateien und eingefügter Inhalt werden lokal verarbeitet und beim Schließen gelöscht. Es werden keine Zugangsdaten, Downloads, Cache-Änderungen oder Gastvorgänge benötigt.",noResult:"Kein Ergebnis geladen.",checking:"Dokumentstruktur wird geprüft…",unverified:"Ungeprüftes Dokument",development:"Entwicklungsbeispiel — nicht für Produktion",notProvided:"Nicht angegeben",none:"Keine",truncated:"für Anzeige gekürzt",coreStatus:"Core-Status",steamosTarget:"SteamOS-Ziel",kernelTarget:"Kernel-Ziel",architecture:"Architektur",exactSupport:"Von Core gemeldete exakte Zielunterstützung",reason:"Grund",message:"Meldung",publicationTag:"Veröffentlichungs-Tag",publishedSteamOS:"Veröffentlichtes SteamOS",publishedKernel:"Veröffentlichter Kernel",publishedNvidia:"Veröffentlichtes NVIDIA",artifactName:"Artefaktname",artifactTrust:"Von Core gemeldetes Artefaktvertrauen",requiredVerification:"Erforderliche Prüfung",nextAction:"Von Core gemeldeter nächster Schritt",actionArchitecture:"Aktionsarchitektur",kernelPolicy:"Kernel-Richtlinie",availableGenerations:"Verfügbare Generationen — Entwicklungsbeispiel",selectedGeneration:"Ausgewählte Generation — Entwicklungsbeispiel",activeGeneration:"Aktive Generation — Entwicklungsbeispiel",lastKnownGood:"Letzte bekannte gute Generation — Entwicklungsbeispiel"},
  "ja-JP": {...en,language:"言語",systemDefault:"システム設定",languageHelp:"表示言語を選ぶか、システム言語に従います。",dialogTitle:"Core 互換性インスペクター",close:"閉じる",notice:"読み取り専用プレビューです。文書構造は検査されますが、真正性は確認されません。互換という結果だけでは、ビルド、ダウンロード、または有効化は許可されません。",fileOpen:"ローカルの Core リゾルバー JSON を開く（最大 1 MiB）",documentLabel:"Core リゾルバー JSON（最大 1 MiB）",placeholder:"Core リゾルバー結果を貼り付け",inspect:"貼り付けた結果を検査",clear:"消去",fixtureHelp:"開発用フィクスチャは本番用ではなく、デバッグビルドでのみ利用できます。",compatibleFixture:"互換フィクスチャ",noArtifactFixture:"成果物なしフィクスチャ",privacy:"選択したファイルと貼り付けた内容はローカルで処理され、この画面を閉じると消去されます。認証情報、ダウンロード、キャッシュ変更、ゲスト操作は不要です。",noResult:"結果は読み込まれていません。",checking:"文書構造を確認中…",unverified:"未検証の文書",development:"開発用フィクスチャ — 本番利用不可",notProvided:"未指定",none:"なし",truncated:"表示用に省略",coreStatus:"Core 状態",steamosTarget:"SteamOS 対象",kernelTarget:"カーネル対象",architecture:"アーキテクチャ",exactSupport:"Core が報告した完全一致対応",reason:"理由",message:"メッセージ",publicationTag:"公開タグ",publishedSteamOS:"公開 SteamOS",publishedKernel:"公開カーネル",publishedNvidia:"公開 NVIDIA",artifactName:"成果物名",artifactTrust:"Core が報告した成果物の信頼状態",requiredVerification:"必要な検証",nextAction:"Core が報告した次の操作",actionArchitecture:"操作アーキテクチャ",kernelPolicy:"カーネル方針",availableGenerations:"利用可能な世代 — 開発用フィクスチャ",selectedGeneration:"選択中の世代 — 開発用フィクスチャ",activeGeneration:"有効な世代 — 開発用フィクスチャ",lastKnownGood:"最終正常世代 — 開発用フィクスチャ"},
  ar: {...en,language:"اللغة",systemDefault:"إعداد النظام",languageHelp:"اختر لغة الواجهة أو اتبع لغة النظام.",dialogTitle:"فاحص توافق Core",close:"إغلاق",notice:"هذه معاينة للقراءة فقط. يُفحص تركيب المستند، لكن لا تُثبت أصالته. نتيجة التوافق لا تسمح بالبناء أو التنزيل أو التفعيل.",fileOpen:"فتح ملف JSON محلي لمحلّل Core (حتى 1 MiB)",documentLabel:"JSON لمحلّل Core (حتى 1 MiB)",placeholder:"ألصق نتيجة محلّل Core",inspect:"فحص النتيجة الملصقة",clear:"مسح",fixtureHelp:"عينات التطوير ليست للإنتاج ولا تتوفر إلا في إصدارات التصحيح.",compatibleFixture:"عينة متوافقة",noArtifactFixture:"عينة بلا حزمة",privacy:"تُعالج الملفات المحددة والمحتويات الملصقة محليًا وتُمسح عند إغلاق الفاحص. لا حاجة إلى بيانات اعتماد أو تنزيلات أو تغييرات في الذاكرة المؤقتة أو عمليات ضيف.",noResult:"لم تُحمّل نتيجة.",checking:"جارٍ فحص تركيب المستند…",unverified:"مستند غير موثّق",development:"عينة تطوير — ليست للإنتاج",notProvided:"غير متوفر",none:"لا شيء",truncated:"مختصر للعرض",coreStatus:"حالة Core",steamosTarget:"هدف SteamOS",kernelTarget:"هدف النواة",architecture:"البنية",exactSupport:"دعم الهدف الدقيق كما أبلغ Core",reason:"السبب",message:"الرسالة",publicationTag:"وسم النشر",publishedSteamOS:"SteamOS المنشور",publishedKernel:"النواة المنشورة",publishedNvidia:"NVIDIA المنشور",artifactName:"اسم الحزمة",artifactTrust:"ثقة الحزمة كما أبلغ Core",requiredVerification:"التحقق المطلوب",nextAction:"الإجراء التالي كما أبلغ Core",actionArchitecture:"بنية الإجراء",kernelPolicy:"سياسة النواة",availableGenerations:"الأجيال المتاحة — عينة تطوير",selectedGeneration:"الجيل المحدد — عينة تطوير",activeGeneration:"الجيل النشط — عينة تطوير",lastKnownGood:"آخر جيل سليم — عينة تطوير"}
};
let activeLocale="en-US";
export function validateCatalog(candidate, fallback=en){
  if(!candidate||typeof candidate!=="object"||Array.isArray(candidate))return false;
  const expected=Object.keys(fallback).sort();
  const actual=Object.keys(candidate).sort();
  return actual.length===expected.length&&actual.every((key,index)=>key===expected[index])&&actual.every(key=>typeof candidate[key]==="string"&&candidate[key].length>0&&!/[<>]/.test(candidate[key]));
}
for(const [locale,entries] of Object.entries(catalogs)){if(!validateCatalog(entries))throw new Error(`Invalid built-in locale catalog: ${locale}`);}
export function resolveLocale(choice,languages=[]){if(choice&&choice!=="system"&&SUPPORTED_LOCALES.includes(choice))return choice;for(const raw of languages||[]){const value=String(raw);const match=SUPPORTED_LOCALES.find(x=>x.toLowerCase()===value.toLowerCase())||SUPPORTED_LOCALES.find(x=>x.split("-")[0]===value.split("-")[0].toLowerCase());if(match)return match;}return "en-US";}
export function translate(key,locale=activeLocale){return catalogs[locale]?.[key]??en[key]??key;}
export function catalog(locale){return catalogs[locale];}
const ids={"locale-label":"language","locale-system-option":"systemDefault","locale-help":"languageHelp","compatibility-title":"dialogTitle","compatibility-close":"close","compatibility-notice":"notice","compatibility-file-open":"fileOpen","compatibility-document-label":"documentLabel","compatibility-inspect":"inspect","compatibility-clear":"clear","compatibility-fixture-help":"fixtureHelp","compatibility-fixture-compatible":"compatibleFixture","compatibility-fixture-no-artifact":"noArtifactFixture","compatibility-privacy":"privacy"};
export function installLocale(doc=document,nav=navigator,storage=localStorage){let choice="system";try{choice=storage.getItem(STORAGE_KEY)||"system";}catch{}const select=doc.getElementById("locale-select");const notify=()=>{if(doc.dispatchEvent&&doc.defaultView?.CustomEvent)doc.dispatchEvent(new doc.defaultView.CustomEvent("opemos-locale-change"));};const apply=()=>{activeLocale=resolveLocale(choice,nav.languages||[nav.language]);doc.documentElement.lang=activeLocale;doc.documentElement.dir=activeLocale==="ar"?"rtl":"ltr";for(const [id,key] of Object.entries(ids)){const node=doc.getElementById(id);if(node)node.textContent=translate(key);}const input=doc.getElementById("compatibility-document");if(input)input.placeholder=translate("placeholder");if(select)select.value=choice;};if(select)select.addEventListener("change",()=>{choice=select.value;try{choice==="system"?storage.removeItem(STORAGE_KEY):storage.setItem(STORAGE_KEY,choice);}catch{}apply();notify();});doc.defaultView?.addEventListener?.("storage",event=>{if(event.key!==STORAGE_KEY)return;choice=event.newValue||"system";apply();notify();});apply();return{get locale(){return activeLocale;},apply};}
